project_name: saml-auth-proxy
gomod:
  proxy: true
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm
archives:
  - replacements:
      darwin: macosx
      386: x86_32
      amd64: x86_64
    format: binary
    files:
      - none*
dockers:
  - image_templates:
      - "kyori/{{.ProjectName}}:latest"
      - "kyori/{{.ProjectName}}:{{ .Tag }}"
    dockerfile: Dockerfile.release
    use: buildx
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "snapshot-{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^misc:'
    - '^ci:'
    - '^test:'
release:
  prerelease: auto
