project_name: saml-auth-proxy
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm
archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{- title .Os }}_
      {{- if eq .Arch "darwin" }}macosx
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format: binary
    files:
      - none*
dockers:
  - image_templates:
      - "kyori/{{.ProjectName}}:latest"
      - "kyori/{{.ProjectName}}:{{ .Tag }}"
    dockerfile: Dockerfile.release
    use: buildx
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "snapshot-{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^misc:'
    - '^ci:'
    - '^test:'
release:
  prerelease: auto
